# Generated by Django 5.2.4 on 2025-07-24 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер ТТН')),
                ('date', models.DateField(verbose_name='Дата накладной')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
        ),
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/', verbose_name='Файл Excel')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработан')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='parser.invoice', verbose_name='Накладная')),
            ],
        ),
        migrations.CreateModel(
            name='ScanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование товара')),
                ('unit', models.CharField(max_length=50, verbose_name='Единица измерения')),
                ('quantity', models.FloatField(verbose_name='Количество')),
                ('price', models.FloatField(verbose_name='Цена, руб.коп.')),
                ('total', models.FloatField(verbose_name='Стоимость, руб.коп.')),
                ('vat_rate', models.CharField(max_length=20, verbose_name='Ставка НДС, %')),
                ('vat_amount', models.FloatField(verbose_name='Сумма НДС, руб.коп.')),
                ('total_with_vat', models.FloatField(verbose_name='Стоимость с НДС, руб.коп.')),
                ('places', models.CharField(blank=True, max_length=100, verbose_name='Количество грузовых мест')),
                ('weight', models.CharField(blank=True, max_length=100, verbose_name='Масса груза')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('excel_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='parser.excelfile', verbose_name='Исходный файл')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='parser.invoice', verbose_name='Накладная')),
            ],
        ),
    ]
