# Generated by Django 5.2.4 on 2025-07-24 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование товара')),
                ('quantity', models.FloatField(verbose_name='Количество')),
                ('price', models.FloatField(verbose_name='Цена, руб.коп.')),
                ('total', models.FloatField(blank=True, null=True, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('excel_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='parser.excelfile', verbose_name='Исходный файл')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='parser.invoice', verbose_name='Накладная')),
            ],
        ),
        migrations.DeleteModel(
            name='ScanData',
        ),
    ]
