# Generated by Django 5.2.4 on 2025-07-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttn_number', models.CharField(max_length=50, verbose_name='Номер ТТН')),
                ('price_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код из прайса')),
                ('price_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип из прайса')),
                ('price_article', models.CharField(blank=True, max_length=100, null=True, verbose_name='Артикул из прайса')),
                ('price_name', models.TextField(blank=True, null=True, verbose_name='Наименование из прайса')),
                ('price1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена 1 из прайса')),
                ('price2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена 2 из прайса')),
                ('price_clear', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за ед. из прайса')),
                ('product_name', models.TextField(verbose_name='Наименование из накладной')),
                ('product_quantity', models.FloatField(verbose_name='Количество из накладной')),
                ('product_price', models.FloatField(verbose_name='Цена из накладной')),
                ('match_status', models.CharField(choices=[('full', 'Полное'), ('partial', 'Частичное'), ('none', 'Нет')], max_length=20, verbose_name='Статус соответствия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Финальная выборка',
                'verbose_name_plural': 'Финальные выборки',
                'indexes': [models.Index(fields=['ttn_number'], name='parser_fina_ttn_num_cb6455_idx'), models.Index(fields=['price_code'], name='parser_fina_price_c_cb3800_idx'), models.Index(fields=['price_article'], name='parser_fina_price_a_4b027d_idx')],
            },
        ),
    ]
