# Generated by Django 5.2.4 on 2025-07-24 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_product_delete_scandata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер ТТН')),
                ('date', models.DateField(verbose_name='Дата ТТН')),
                ('status', models.CharField(choices=[('in_progress', 'В обработке'), ('completed', 'Завершена'), ('canceled', 'Отменена')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('total_products', models.PositiveIntegerField(default=0, verbose_name='Всего товаров')),
                ('processed_files', models.PositiveIntegerField(default=0, verbose_name='Обработано файлов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'ТТН',
                'verbose_name_plural': 'ТТН',
                'ordering': ['-date', 'number'],
            },
        ),
        migrations.AddField(
            model_name='excelfile',
            name='page_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер страницы'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номер накладной'),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='ttn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excel_files', to='parser.ttn', verbose_name='ТТН'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ttn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='parser.ttn', verbose_name='ТТН'),
        ),
        migrations.AddField(
            model_name='product',
            name='ttn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='parser.ttn', verbose_name='ТТН'),
        ),
    ]
