# Generated by Django 5.2.4 on 2025-07-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_ttn_excelfile_page_number_alter_invoice_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код товара')),
                ('type', models.CharField(blank=True, max_length=100, verbose_name='Тип')),
                ('article', models.CharField(blank=True, max_length=100, verbose_name='Артикул')),
                ('name', models.TextField(verbose_name='Наименование')),
                ('price1', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена 1')),
                ('price2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена 2')),
                ('stock', models.IntegerField(default=0, verbose_name='Остаток')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('price_date', models.DateField(verbose_name='Дата прайса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Прайс',
                'verbose_name_plural': 'Прайсы',
                'ordering': ['code'],
            },
        ),
    ]
